### ISSUE TITLE
Request: Either create 2nd image or alter this image to use the DEV branch of nZEDb

### ISSUE THREAD

**Issue by CollinChaffin** [slydetector/simply-nzedb#102]
Since nZEDb is so unstable and so infrequently tended to I want to request that you base the image or add a new docker image to git clone this DEV branch, which is what they recommend for active fixes:
````
https://github.com/nZEDb/nZEDb/tree/dev
````
I just ran into a final fix after waiting half a year for the predb issues which probably won't even hit their master branch that this docker image is updating to for many months to come.  One can manually begin scripting new git pulls or altering yours, but that kind of defeats the purpose since, if you simply made one change to clone to DEV, you've already got everything in place within the MAKE PULL to then keep it truly updated, but based on what really IS being updated.

**Comment by slydetector** [comment]
I run stable and don't have the time to run a continuously updated dev branch that may break. If you'd like to parameterize the branch that is used (with a default value of the stable branch), feel free to submit a PR.
