### ISSUE TITLE
Errors during make backup

### ISSUE THREAD

**Issue by pdupreez** [slydetector/simply-nzedb#125]
Not sure if it is an error, or by default. Making a first backup it gave me this error.:

pdupreez@vmi149692:~/nzedb$ make backup
Dumping database to ./data/db_backups
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/run/mysqld/mysqld.sock' exists!
Dumping nzedb.

There is no /run/mysqld directory as far as I could tell (in make shell environment or otherwise)

The dumps still seems to complete, the file does exist at the end in ~/nzedb/data/db_backup/

**Comment by slydetector** [comment]
That error message is harmless.  There are two ways to connect to mysql, through a local unix domain socket (the error you're seeing) and then through a TCP socket.  The nzedb code just defaults to using the domain socket first and then uses the TCP socket if that fails.

**Comment by pdupreez** [comment]
Thanks for the response. It worked/is working well.
