### ISSUE TITLE
Update from GitHub

### ISSUE THREAD

**Issue by bungledual** [slydetector/simply-nzedb#16]
Sorry - total noob question. How do I update to latest version without overwriting my DB? I do not know Git commands at all. Looking forward to trying out the import and irc options.

TIA.

**Comment by slydetector** [comment]
Probably worth investing some time in getting to know git a bit - http://rogerdudler.github.io/git-guide/

Starting off from scratch will remove your `data` directory, hence your entire database. I'd start off in a completely new directory with a fresh clone of the latest version, get things up and running, and then copy your old database over to the new one in `./data/var_lib_mysql`.

**Comment by bungledual** [comment]
Will sit down over the weekend and start learning. You can close this one - Thanks.
