### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by MickHere** [slydetector/simply-nzedb#42]
Hi
First off, let me wish you a Merry Christmas :)
For some reason my nzedb keeps freezing at times. Sometimes it will continue after 10 or so mins, other times I have to restart it after a couple hours or so.
I'm not sure if its a memory problem, Tmux problem or what.
When it freezes I get the 504 error when going to the site.
Picture or my Tmux here when frozen. http://i.imgur.com/DZ0kCoz.jpg
My nzedb setup is running on a Intel NUC NUC5PPYH http://www.intel.com.au/content/www/au/en/nuc/nuc-kit-nuc5ppyh.html

Thanks

**Comment by slydetector** [comment]
A ``504`` error is when a request takes too long and nginx times out.  More than likely, you have requests blocked on database queries. Switch over to the `mytop` pane in tmux and grab a screenshot when this happens. One of the columns is the number of seconds elapsed for a query. Other queries are most likely blocked on a single query that is taking a long time to execute. How much RAM do you have? SSD or spinning rust?
