### ISSUE TITLE
pane is dead

### ISSUE THREAD

**Issue by fableman73** [slydetector/simply-nzedb#45]
1. Great work!!!!
Installed 2 days ago and everything feels good..

Just a question.. make attach, I noticed this message: " pane is dead " is that an error, do I need to do something?

**Comment by slydetector** [comment]
Sometimes there is a delay between `make start` and `make attach` during which you might get the `pane is dead` error. Just wait a few secs for things to get rolling and then `make attach` should eventually work. If that is not the case, please post more details.

**Comment by fableman73** [comment]
It's not that.
Shows "pane is dead" message from time to time but everything works i guess..

**Comment by slydetector** [comment]
Yeah, that is normal and the way that the tmux scripts work :smile:
