### ISSUE TITLE
Web Setup

### ISSUE THREAD

**Issue by LennyM8472** [slydetector/simply-nzedb#46]
Hi,

first thanks for this setup!

Everything works fine until executing "Web_Setup" and results in following error:

`[/share/MD0_DATA/Applications/simply_nzedb/nzedb] # bin/web_setup
rm: can't remove 'web_setup.log': No such file or directory
bin/nzedb_lib: line 8: syntax error near unexpected token `&'`

best regards
Lenny

**Comment by slydetector** [comment]
What is the output of `bash --version`?

**Comment by LennyM8472** [comment]
`[~] # bash --version
GNU bash, version 3.2.57(1)-release (x86_64-QNAP-linux-gnu)
Copyright (C) 2007 Free Software Foundation, Inc.`

**Comment by slydetector** [comment]
Looks like the `|&` operator that is causing issues was introduced in bash 4.0+

http://bashcookbook.com/bashinfo/source/bash-4.0/CHANGES

Can you easily upgrade your version of `bash`?

**Comment by slydetector** [comment]
Should be fixed now.
