### ISSUE TITLE
Error with Install

### ISSUE THREAD

**Issue by cheerfull38** [slydetector/simply-nzedb#64]
Everything works until you go hit "make attach" And the install was working the other day. I messed something up and went to install again. Error below:
nzedb$ make attach
no sessions
Makefile:30: recipe for target 'attach' failed
make: *** [attach] Error 1

By the way this is awesome work!

**Comment by slydetector** [comment]
The upgrade to nzedb 0.7.0.0 didn't go as smooth as expected. Working on a fix.

**Comment by cheerfull38** [comment]
Thank You for your very quick response. your work has made this VERY easy! Eagerly awaiting the results of your fix.

**Comment by slydetector** [comment]
Fixed in #65.

**Comment by cheerfull38** [comment]
Awesome and it is verified working on my side! Super thanks for fixing this and what you have written is excellent! Thanks again.

**Comment by slydetector** [comment]
Enjoy!
