### ISSUE TITLE
Question for increasing InnoDB: innodb_buffer_pool_size

### ISSUE THREAD

**Issue by cheerfull38** [slydetector/simply-nzedb#66]
I would like to change the settings for in my.cnf file to use up to 3G of ram. I looked at the existing file /etc/mysql/ and it would appear this is not the correct file being used to make the changes in. What is the correct file location to change my my.cnf settings for  innodb_buffer_pool_size = 3g from the 256M it is set to now?

Thanks in advance

**Comment by slydetector** [comment]
Just create a file like so:

```
$ cat data/etc_mysql_conf.d/nzedb.cnf 
[mysqld]
key_buffer_size = 2G
innodb_buffer_pool_size = 8G
```
