### ISSUE TITLE
SQL username and password

### ISSUE THREAD

**Issue by joetlawson** [slydetector/simply-nzedb#72]
This may be a newb question and trust me I'm a newb when it comes to linux and docker etc. What is the username and password for the DB I do not recall setting any of this up. Also thank you for the easy setup instructions I spent more than two weeks trying to do this manually and failing each time. Also I notice there is only one group active is that by design if so what do I do to activate additional groups? I tried using the nzedb with no luck as posted by dilbaggins.

PS: I have tried searching for this solution on my own since yesterday! It seems there are no real guides written for newbs who are new to this scene!

**Comment by slydetector** [comment]
https://github.com/slydetector/simply-nzedb/blob/master/etc/simply_nzedb.conf.example#L19

nzedb -> profile -> admin panel -> site settings -> groups -> view

exploring is so much more fun than reading a guide! :smile:

**Comment by joetlawson** [comment]
slydetector,

Thank you for the help I found the groups prior what threw me off was all the groups status was in green and at first glance it appeared they said active when in fact they said activate. My brain automatically associated green with good to go I blame signal lights!
