### ISSUE TITLE
Need assistance with slydetector/simply-nzedb-mariadb please

### ISSUE THREAD

**Issue by blindguy** [slydetector/simply-nzedb#80]
My slydetector/simply-nzedb-mariadb container is always restating and I can't bin/apply_defaults as it says the container is restarting.

Not sure how to check logs or see had is going on, any thoughts?

f6fd28eee9ce        slydetector/simply-nzedb-mariadb   "moduser-entrypoin..."   2 minutes ago       Restarting (1) About a minute ago                                                                                            nzedb_database_1

Applying sane defaults to settings database table
Error response from daemon: Container f6fd28eee9ce8d5426f4134e17cfcd71948d28dfbbd373280833810e3916f827 is restarting, wait until the container is running

**Comment by blindguy** [comment]
Found some logs:

Initializing database
mkdir: cannot create directory '/var/lib/mysql//mysql': No space left on device
Fatal error Can't create database directory '/var/lib/mysql//mysql'

in common.yml we have 
  database:
    image: slydetector/simply-nzedb-mariadb
    restart: unless-stopped
    volumes:
      - $PWD/data/var_lib_mysql:/var/lib/mysql
      - $PWD/data/etc_mysql_conf.d:/etc/mysql/conf.d
      - $PWD/data/mysql_user:/mysql_user

I'm not sure where the extra /mysql is comming from

**Comment by slydetector** [comment]
Try `make pull` to pull the latest images and try again. Also, just not to overlook the obvious, you did make sure that you have ample space in the volume with the current directory, right? `df -kh`

**Comment by blindguy** [comment]
Ran a make pull and things are now working.  I am at the lgoin prompt, thanks.
