### ISSUE TITLE
3 questions (probably easier answers)

### ISSUE THREAD

**Issue by dilbaggins** [slydetector/simply-nzedb#81]
1) how do i change the default logo/favicon so every boot i can use my own logo
2) getting a php memory limit issue (when i update and rerun its still using the old value (not the -1 it should)
3) why does tmux look like this by default ( notice the "q" and "x" i enabled powerline, perhaps these fonts need to be added?)
![image](https://user-images.githubusercontent.com/3989347/27260837-ab2f5b34-5403-11e7-87d8-15ad5fa806e4.png)

**Comment by slydetector** [comment]
1. No idea
2. Hmm, will have to look in to that. Think I'm having the same issue.
3. I've always wondered why the lines were letters. Another thing worth looking into.

**Comment by slydetector** [comment]
You're on your own with 1. 
2 and 3 are fixed.
