### ISSUE TITLE
everything is dead?

### ISSUE THREAD

**Issue by DaveG9856** [slydetector/simply-nzedb#86]
Followed instructions to the letter, it all loads fine import the pre-db all goes well then everything goes dead all panes are dead and nothings going on.

1) how do we restart panes and 
2) why is this happening and how to stop it.

servers stats i7-2600 16gb ram and 7TB hd on 10gb line

**Comment by slydetector** [comment]
1. `make start`
2. need logs - `make logs` would be a good start
