### ISSUE TITLE
PHP Issue

### ISSUE THREAD

**Issue by kbbeer** [slydetector/simply-nzedb#92]
Hello - When I run php update_binaries.php or php update_releases.php I receive the following error - 

PHP Warning:  include(/var/www/nZEDb/libraries/lithium/core/Libraries.php): failed to open stream: No such file or directory in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 72
PHP Warning:  include(): Failed opening '/var/www/nZEDb/libraries/lithium/core/Libraries.php' for inclusion (include_path='.:/usr/share/php') in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 72
PHP Fatal error:  Uncaught ErrorException: Lithium core could not be found.  Check the value of LITHIUM_LIBRARY_PATH in /var/www/nZEDb/app/config/bootstrap/libraries.php.  It should point to the directory containing your /libraries directory. in /var/www/nZEDb/app/config/bootstrap/libraries.php:76
Stack trace:
#0 /var/www/nZEDb/app/config/bootstrap.php(34): require_once()
#1 /var/www/nZEDb/bootstrap.php(19): require_once('/var/www/nZEDb/...')
#2 /var/www/nZEDb/misc/update/update_releases.php(2): require_once('/var/www/nZEDb/...')
#3 {main}
  thrown in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 76

**Comment by slydetector** [comment]
Run and paste output:
```$ make shell```
```$ which php```
```$ php --version```
```$ find / -name Libraries.php```
```$ env | grep -vi password | sort```

**Comment by kbbeer** [comment]
Thanks for the help, I deleted my local username from below.

@Ubuntu-HP:/var/www/nZEDb/misc/update$ sudo make shell
make: *** No rule to make target 'shell'.  Stop.

@Ubuntu-HP:/var/www/nZEDb/misc/update$ sudo which php
/usr/bin/php

@Ubuntu-HP:/var/www/nZEDb/misc/update$ sudo php --version
PHP 7.0.22-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies

@Ubuntu-HP:/var/www/nZEDb/misc/update$ sudo find / -name libraries.php
find: ‘/run/user/1000/gvfs’: Permission denied
/var/www/nZEDb/app/config/bootstrap/libraries.php
/var/lib/docker/aufs/diff/df5c7ed27c988781c57f9437027900650f660f3b468d7c775ebc0d7cf9f2c190/var/www/nZEDb/app/config/bootstrap/libraries.php
/var/lib/docker/aufs/mnt/2b4a6bc600d7a24aa860715543d2cb94b69779aae393039f3df6cf785766254d/var/www/nZEDb/app/config/bootstrap/libraries.php

@Ubuntu-HP:/var/www/nZEDb/misc/update$ sudo env | grep -vi password | sort
DISPLAY=:0
HOME=/home/
LANG=en_US.UTF-8
LANGUAGE=en_US
LOGNAME=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
SHELL=/bin/bash
SUDO_COMMAND=/usr/bin/env
SUDO_GID=33
SUDO_UID=1000
SUDO_USER=
TERM=xterm-256color
USERNAME=root
USER=root
XAUTHORITY=/home//.Xauthority

**Comment by slydetector** [comment]
That first command, ```sudo make shell``` failed because it requires nzedb  to be running. Try  ```sudo make start``` first then the whole list of commands again.

**Comment by kbbeer** [comment]
Looks like that command fails...

@Ubuntu-HP:/var/www/nZEDb$ sudo make start
make: *** No rule to make target 'start'.  Stop.

**Comment by slydetector** [comment]
Have you followed the instructions for installation?
