### ISSUE TITLE
par2

### ISSUE THREAD

**Issue by ogg1e** [slydetector/simply-nzedb#94]
Is there a reason par2 isn't part of the image?

**Comment by slydetector** [comment]
Can't say that I've had to use it for anything to get nzedb working correctly. What utility would it provide?

**Comment by ogg1e** [comment]
In admin under post processing, there's a section to use par2 for batter naming:

Whether to attempt to find a better name for releases in misc->other using the PAR2 file.NOTE: this can be slow depending on the group!

**Comment by slydetector** [comment]
Fixed in #96 and #97
