### ISSUE TITLE
unable to update db to innodb 

### ISSUE THREAD

**Issue by ogg1e** [slydetector/simply-nzedb#95]
Since my.cnf isn't external to docker, you cannot update the storage to innodb. 

That's one of the big recommendations is to do that, and you need to update my.cnf setting : innodb_file_per_table

**Comment by slydetector** [comment]
You can customize mysql settings by creating a cnf file in ```data/etc_mysql_conf.d/```.  For example, this is my ```data/etc_mysql_conf.d/nzedb.cnf``` file

```
[mysqld]
key_buffer_size = 2G
innodb_buffer_pool_size = 8G
group_concat_max_len = 32768
```

**Comment by slydetector** [comment]
Docs updated in 83cf9e416519f97cb558bb843396f99431b495dd
