### ISSUE TITLE
Major cert issue

### ISSUE THREAD

**Issue by CollinChaffin** [slydetector/simply-nzedb#99]
So can you elaborate if you simply have ZERO TLS/cert verification turned on in nzedb, and if not exactly what magic above and beyond your make scripts you're using since every single MAKE STOP/START results in the downloaded and required cacert.pem in standard etc/ssl (which your build is even still using) being deleted every restart.  This results in a 100% failure to connect to any SSL based NNTP server.

**Comment by CollinChaffin** [comment]
I have done more testing, and what this requires for the fix is to add a new VOLUMES entry specifically to a pre-downloaded copy of the certs.  Otherwise, at every make restart, you lose the cert PEM, and all TLS (pretty much everything) if you are using SSL for your NNTP servers, winds up failing until you re-curl download it.

**Comment by slydetector** [comment]
I use SSL when connecting to NNTP servers and have no issues whatsoever. Steps to reproduce the issue or errors from a log file would help narrow down the issue you're having.

**Comment by slydetector** [comment]
Re-open if you have more supporting details.
